/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cesar
 */
public class InstruccionesInternas extends javax.swing.JInternalFrame {

    /**
     * Creates new form InstruccionesInternas
     */
    public InstruccionesInternas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jScrollPane1.setForeground(new java.awt.Color(255, 0, 51));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 0, 51));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Este programa consiste basicamente en un formulario, \nAl cual se accede por medio del jToolBar.\n\nEs un formulario basico, en el cual se utilizo el\njFormattedTextField para validar que el usuario solo ingrese\nnumeros y cuya extension no sea mayor a 10 (numero de\ntelefono celular). En el jComboBox se ingresa el pais al que\npertenece el individuo que se desea guardar su informacion.\nEsta informacion se ve reflejada a traves de un jTable.\nDentro del jInternalFrame habra un boton el cual abrira un\njDialog, este permitira cambiar el color del texto del jTable, \nal momento de que el usuario de clic en aceptar.\n\nTambien hay dos botones para guardar la informacion como un\narchivo de texto o un archivo de valores separados por comas\n(csv)\n\nEl jDektopPane sirve para contener la ventana interna en\ndonde se presenta la informacion mencionada.\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
